//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace viewmodel.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qoutation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Qoutation()
        {
            this.QoutationDetails = new HashSet<QoutationDetails>();
        }
    
        public int ID { get; set; }
        public int QoutationId { get; set; }
        public string CompanyName { get; set; }
        public string Addres { get; set; }
        public string ContactPerson { get; set; }
        public int phone { get; set; }
        public string mail { get; set; }
        public string CustomerId { get; set; }
        public string TaxNo { get; set; }
        public Nullable<System.DateTime> QoutationDate { get; set; }
        public string QoutationNo { get; set; }
        public Nullable<int> TaxRate { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpDateDate { get; set; }
        public string UpDateBy { get; set; }
        public string Text { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QoutationDetails> QoutationDetails { get; set; }
    }
}
